version : "3.9"
services :
  proyectojenkins : 
    container_name : proyectojenkins
    image : proyectojenkins:v1
    env_file :
      - .env
    build :
      context : .
    ports : 
      - "4003"
    networks : 
      - proyectos-app


  proyectojenkins2 : 
    container_name : proyectojenkins2
    image : proyectojenkins:v1
    env_file :
      - .env  
    ports : 
      - "4003"
    networks : 
      - proyectos-app


  balanceado : 
    container_name : balanceado
    image : balanceado:v1
    env_file :
      - .env
    build :
      context : ./balanceador
    ports : 
      - "4004:80"
    networks : 
      - proyectos-app

 
networks : 
  proyectos-app :